# Generated by Django 3.1 on 2020-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user.png', null=True, upload_to='profile_pictures'),
        ),
    ]
