# Generated by Django 3.1 on 2020-09-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='commented',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='liked',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.answer'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.like'),
        ),
    ]
